create table if not exists patients (
  id bigint generated by default as identity primary key,
  document text not null unique,
  first_name text not null,
  last_name text not null,
  age integer not null,
  sex text not null,
  phone text,
  created_at text not null
);

create table if not exists specialties (
  id bigint primary key,
  name text not null,
  price numeric(10, 2) not null,
  duration_min integer not null,
  room text not null,
  doctor_name text not null
);

create table if not exists appointments (
  id bigint generated by default as identity primary key,
  ticket text not null unique,
  patient_id bigint not null references patients(id),
  specialty_id bigint not null references specialties(id),
  status text not null,
  payment_status text not null,
  triage_status text not null,
  consultation_status text not null,
  pharmacy_status text not null,
  room text,
  scheduled_at text,
  receipt_code text,
  created_at text not null,
  paid_at text
);

create table if not exists triage_records (
  id bigint generated by default as identity primary key,
  appointment_id bigint not null unique references appointments(id),
  temperature numeric(4, 1) not null,
  heart_rate integer not null,
  spo2 integer not null,
  systolic integer not null,
  diastolic integer not null,
  weight numeric(5, 1) not null,
  height numeric(5, 1) not null,
  bmi numeric(5, 2) not null,
  priority text not null,
  risk_score numeric(5, 3) not null,
  risk_label text not null,
  predicted_systolic numeric(5, 1) not null,
  estimated_attention_minutes numeric(5, 1) not null,
  decision_summary text not null,
  analysis_json text not null,
  source text not null,
  captured_at text not null
);

create table if not exists consultations (
  id bigint generated by default as identity primary key,
  appointment_id bigint not null unique references appointments(id),
  doctor_name text not null,
  symptoms text not null,
  diagnosis text not null,
  treatment_notes text not null,
  notes text,
  created_at text not null
);

create table if not exists prescriptions (
  id bigint generated by default as identity primary key,
  appointment_id bigint not null references appointments(id),
  consultation_id bigint not null references consultations(id),
  status text not null,
  total numeric(10, 2) not null,
  created_at text not null,
  dispensed_at text
);

create table if not exists prescription_items (
  id bigint generated by default as identity primary key,
  prescription_id bigint not null references prescriptions(id) on delete cascade,
  medicine text not null,
  dosage text not null,
  frequency text not null,
  days integer not null,
  quantity integer not null,
  unit_price numeric(10, 2) not null
);

create table if not exists settings (
  key text primary key,
  value text
);

create table if not exists audit_events (
  id bigint generated by default as identity primary key,
  event_type text not null,
  entity text not null,
  entity_id bigint,
  message text not null,
  created_at text not null
);

insert into specialties (id, name, price, duration_min, room, doctor_name) values
  (1, 'Medicina General', 55.00, 20, 'C-101', 'Dra. Valeria Ramos'),
  (2, 'Pediatria', 70.00, 20, 'C-102', 'Dr. Mateo Aguilar'),
  (3, 'Cardiologia', 120.00, 30, 'C-201', 'Dra. Camila Torres'),
  (4, 'Dermatologia', 90.00, 20, 'C-202', 'Dr. Alonso Vega'),
  (5, 'Ginecologia', 100.00, 25, 'C-203', 'Dra. Sofia Paredes'),
  (6, 'Traumatologia', 110.00, 25, 'C-204', 'Dr. Diego Salazar')
on conflict (id) do update set
  name = excluded.name,
  price = excluded.price,
  duration_min = excluded.duration_min,
  room = excluded.room,
  doctor_name = excluded.doctor_name;

create index if not exists idx_appointments_patient on appointments(patient_id);
create index if not exists idx_appointments_status on appointments(status);
create index if not exists idx_triage_appointment on triage_records(appointment_id);
create index if not exists idx_prescriptions_status on prescriptions(status);
